/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.btn

import no.nav.btn.kafkaservices.Pond
import no.nav.btn.packet.Packet
import org.apache.kafka.clients.consumer.ConsumerRecord

class MeldingDatabasePond : Pond(listOf("")) {
    override val SERVICE_APP_ID: String
        get() = "btn-melding-lagre-db"

    override fun onRecordRecieved(record: ConsumerRecord<String, Packet>) {

    }

}

fun main() {
    val consumer = MeldingDatabasePond()

    Runtime.getRuntime().addShutdownHook(Thread {
        consumer.stop()
    })

    consumer.start()
}
